# Generated by Django 2.2.14 on 2020-07-31 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_homepage_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="asfd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_asfd",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
